config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :blogs, only: [:index, :new, :create, :edit, :update ,:destroy] do
      collection do
        post :confirm
      end
    end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  resources :poems, only: [:index, :show]

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations"
  }

  resources :users, only: [:index, :show]

  resources :blogs do
    resources :comments
    collection do
      post :confirm
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    # 自分の通知のみ取得、通知は新しい順に並び替える。
    @notifications = Notification.where(user_id: current_user.id).order(created_at: :desc)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  # 作成時刻を通知用に日本用に変更して表示する
  def posted_time(time)
    time > Date.today ? "#{time_ago_in_words(time)}" : time.strftime('%m月%d日')
  end
  #　値によって既読か未読かを表示させる
  def read_status(read)
    if read==false
      "未読"
    else
      "既読"
    end
  end
end

app/views/notifications/index.html.erb
<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<h2>お知らせ</h2>
<ul>
  <% @notifications.each do |notification| %>
  <hr>
    <li>
      <p class="left"><strong><%= read_status(notification.read) %></strong></p>
      <p class="left">
        <%= notification.comment.user.try(:name) %>さんが
        あなたのブログ（<%= link_to "#{notification.comment.blog.title}", blog_path(notification.comment.blog, notification_id: notification.id) %>）にコメントしました。
      </p>
      <p class="right"><%= notification.created_at %></p>
    </li>
  <% end %>
</ul>

</div>
</div>